//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.28 at 12:16:09 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org.fer.angularjs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.fer.angularjs.demo.model;
